### ISSUE TITLE
The Master animation.

### ISSUE THREAD

**Issue by FakelsHub** [rotators/Fo1in2#63] opened 2020-05-12 10:32 UTC
- The Master: plays custom death animation on critical w/ better criticals, despite not actually being dead. He is still targettable, and when he goes to attack his sprite is reverted to the correct one. This happened 5 - 10 times to me with a character with finesse trait, better criticals & sniper perks

**Comment by Lexx2k** [comment] 2020-05-12 11:40
I can't fix this / wouldn't know how to fix this. He has the proto setting to use a special death animation and that's all the influence we have about it.

I mean, I guess we could make a hook script for that, but the problem isn't running the death animation, but preventing the death animation from playing when it shouldn't play .... 

tl;dr -- no idea.

**Comment by FakelsHub** [comment] 2020-05-12 13:44
need attach save game.

**Comment by Lexx2k** [comment] 2020-05-12 14:48
Here is a savegame directly in front of the Master: [SLOT01.zip](https://github.com/rotators/Fo1in2/files/4616321/SLOT01.zip)

I didn't test / do anything else.

**Comment by sumyunggai** [comment] 2020-05-12 15:51
Check out this save; you don't even need to enter dialogue, just start unloading on him with the 223 and you'll see it. This is pretty normal install of Fallout1in2, but full config can be found in [this post](https://www.nma-fallout.com/threads/fallout-et-tu-release-v1-1.218045/page-34#post-4379968).
[SLOT19.zip](https://github.com/rotators/Fo1in2/files/4616692/SLOT19.zip)

**Comment by Lexx2k** [comment] 2020-05-12 16:03
Your savegame only works if your mod is enabled, and then I can reproduce the Master bug.

However, here is the thing: You didn't start a new game when working on your mod, thus it is now entirely possible that your mod is causing these effects and it's not actually a vanilla bug.

**Comment by sumyunggai** [comment] 2020-05-12 16:15
Is your character a full copy of mine? SPECIAL, traits, perks and skills? 

Keep in mind my mod is item .pro edits, and addition of the animated containers FRMs and some FOT item frms. I didn't touch the character animations, so I'm not sure how that could contribute to this bug.

**Comment by Lexx2k** [comment] 2020-08-06 05:02
Fixed with https://github.com/rotators/Fo1in2/commit/e40b6b12ed672e2b0e9bcc70e2384d1af19aa102
He was missing his critical hit tables and was still using Frank Horrigan. 
Unlike the Master, Horrigan can be knocked down - thing is, the Master only has one "knocked down and die"-animation, which also includes his cruel death. Thus, whenever you get a critical and floor him, he would "die". With the new crit tables, he can't be knocked down anymore and the bug is gone.

**Closed by Lexx2k** 2020-08-06 05:02 UTC
Labels: bug
